### ISSUE TITLE
How should we balance GPA vs numTrackers in grading first parties?

### ISSUE THREAD

**Issue by edfelten** [edfelten/Tracking-Report-Card#9]
The current formula is essentially  GPA - sqrt(numTrackers) + correctionFactor,  where GPA is the average grade of the trackers on the site, and the correction factor is set so that the average grade of first parties equals the average grade of the third parties we know about.

The question is whether we want to put different relative weights on GPA vs. sqrt(numTrackers).

**Comment by ddturner** [comment]
This may be harsh, but shouldn't a site get an A only if it's clean and clear of tracking? That would make it a non-continuous scale. That is, A if only a certain condition is met, then scale from B to F?

**Comment by edfelten** [comment]
After a conversation with Claire, decided to cut the coefficient on sqrt to 0.5.

**Comment by ddturner** [comment]
We'd all have been lost without Claire.
